version: "3"
services:
  frontend:
    build:
      context: ./client
    image: keemba/docker-client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"
    stdin_open: true
    mem_limit: 128m
    networks:
      - my_network1

  nginx:
    restart: always
    build:
      context: ./nginx
    image: keemba/docker-nginx
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - my_network1

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./root/certbot/conf:/etc/letsencrypt
      - ./root/certbot/www:/var/www/certbot
    networks:
      - my_network1
  backend:
    build:
      context: ./server
    image: keemba/docker-server
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - "4000:4000"
    mem_limit: 128m
    networks:
      - my_network1
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_PORT: ${POSTGRES_PORT}

networks:
  my_network1:
    driver: bridge
