version: "3"
services:
  frontend:
    image: keemba/docker-client
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true
    mem_limit: 128m

  nginx:
    restart: always
    image: keemba/docker-nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  backend:
    image: keemba/docker-server
    volumes:
      - /app/node_modules
      - ./server:/app
    mem_limit: 128m
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - HASH_ROUNDS=${HASH_ROUNDS}
      - PROTOCOL=${PROTOCOL}
      - HOST=${HOST}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
      - GOOGLE_OAUTH_REDIRECT_URL=${GOOGLE_OAUTH_REDIRECT_URL}
      - AWS_BUCKET_ACCESS_KEY=${AWS_BUCKET_ACCESS_KEY}
      - AWS_BUCKET_SECRET_ACCESS_KEY=${AWS_BUCKET_SECRET_ACCESS_KEY}
      - AWS_S3_REGION=${AWS_S3_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
