version: "3"
services:
  frontend:
    build:
      context: ./client
    image: keemba/docker-client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"
    stdin_open: true
    mem_limit: 128m

  nginx:
    restart: always
    build:
      context: ./nginx
    image: keemba/docker-nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  backend:
    build:
      context: ./server
    image: keemba/docker-server
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - "4000:4000"
    mem_limit: 128m
    environment:
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_ROOT_PASSWORD: $POSTGRES_ROOT_PASSWORD
      POSTGRES_DATABASE: $POSTGRES_DATABASE
      POSTGRES_PORT: $POSTGRES_PORT
