version: "3"
services:
  frontend:
    image: keemba/docker-client
    container_name: frontend
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true
    mem_limit: 128m

  nginx:
    restart: always
    container_name: nginx
    image: keemba/docker-nginx
    ports:
      - "80:80"

  backend:
    image: keemba/docker-server
    container_name: backend
    volumes:
      - /app/node_modules
      - ./server:/app
    mem_limit: 128m
    environment:
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_ROOT_PASSWORD: $POSTGRES_ROOT_PASSWORD
      POSTGRES_DATABASE: $POSTGRES_DATABASE
      POSTGRES_PORT: $POSTGRES_PORT
