version: "3"
services:
  frontend:
    image: keemba/docker-client
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true
    mem_limit: 128m

  nginx:
    restart: always
    image: keemba/docker-nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  backend:
    image: keemba/docker-server
    volumes:
      - /app/node_modules
      - ./server:/app
    mem_limit: 128m
    environment:
      POSTGRES_HOST: react-nest-app-db.cn48sgko2q4b.ap-northeast-2.rds.amazonaws.com
      POSTGRES_USER: sup_kimba
      POSTGRES_ROOT_PASSWORD: tntls1234
      POSTGRES_DATABASE: react-nest-app-db
      POSTGRES_PORT: 5432
