version: "3"
services:
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3000:80"

  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    container_name: app_server
    volumes:
      - /app/node_modules
      - ./server:/app

  postgres:
    image: postgres:15
    restart: always
    volumes:
      - ./server/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sub_kimba
      POSTGRES_PASSWORD: tntls1!@
      POSTGRES_DB: react-nest-app
