version: "3"
services:
  frontend:
    image: keemba/docker-client
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true
    mem_limit: 128m

  nginx:
    restart: always
    image: keemba/docker-nginx
    ports:
      - "80:80"

  backend:
    image: keemba/docker-server
    volumes:
      - /app/node_modules
      - ./server:/app
    mem_limit: 128m
