version: "3"
services:
  frontend:
    image: keemba/react-nest-app-frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    mem_limit: 128m

  nginx:
    restart: always
    image: keemba/react-nest-app-nginx
    ports:
      - "80:80"

  backend:
    image: keemba/react-nest-app-backend
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    mem_limit: 128m
    environment:
      POSTGRES_HOST: $MYSQL_HOST
      POSTGRES_USER: $MYSQL_USER
      POSTGRES_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      POSTGRES_DATABASE: $MYSQL_DATABASE
      POSTGRES_PORT: $MYSQL_PORT
