version: "3"
services:
  client:
    image: keemba/docker-client
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true
    mem_limit: 128m

  nginx:
    restart: always
    image: keemba/docker-nginx
    ports:
      - "80:80"

  server:
    image: keemba/docker-server
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./server:/app
    mem_limit: 128m
    environment:
      POSTGRES_HOST: $MYSQL_HOST
      POSTGRES_USER: $MYSQL_USER
      POSTGRES_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      POSTGRES_DATABASE: $MYSQL_DATABASE
      POSTGRES_PORT: $MYSQL_PORT
