services:
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: sub_kimba
      POSTGRES_PASSWORD: tntls1!@
      POSTGRES_DB: react-nest-app
