name: Deploy react-nest-app
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setting .env
        run: |
          echo "REACT_APP_BASE_URL=${{ secrets.REACT_APP_BASE_URL }}" >> .env
          echo "REACT_APP_SOCKET_URL=${{ secrets.REACT_APP_SOCKET_URL }}" >> .env
          echo "REACT_APP_GOOGLE_URL=${{ secrets.REACT_APP_GOOGLE_URL }}" >> .env
          echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> .env
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> .env

      - name: 환경 변수 설정
        env:
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
          REACT_APP_SOCKET_URL: ${{ secrets.REACT_APP_SOCKET_URL }}
          REACT_APP_GOOGLE_URL: ${{ secrets.REACT_APP_GOOGLE_URL }}
        run: |
          echo "환경 변수가 설정되었습니다."

      - run: docker build -t keemba/docker-client ./client
      - run: docker build -t keemba/docker-nginx ./nginx
      - run: docker build -t keemba/docker-server ./server

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - run: docker push keemba/docker-client
      - run: docker push keemba/docker-nginx
      - run: docker push keemba/docker-server

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          key: ${{ secrets.EC2_KEY }}
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          script: |
            sudo docker system prune -af
            docker pull keemba/docker-client
            docker pull keemba/docker-nginx
            docker pull keemba/docker-server
            docker-compose down
            docker-compose up -d
