name: Deploy react-nest-app
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Setting .env
        run: |
          echo "REACT_APP_GOOGLE_CLIENTID=${{ secrets.REACT_APP_BASE_URL }}" >> .env
          echo "REACT_APP_GOOGLE_CLIENTID=${{ secrets.REACT_APP_SOCKET_URL }}" >> .env

      - run: docker build -t keemba/docker-client ./client
      - run: docker build -t keemba/docker-nginx ./nginx
      - run: docker build -t keemba/docker-server ./server

      - run: docker push keemba/docker-client
      - run: docker push keemba/docker-nginx
      - run: docker push keemba/docker-server

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: react-nest-test-docker-app
          environment_name: React-nest-test-docker-app-env
          existing_bucket_name: elasticbeanstalk-ap-northeast-2-883387025513
          region: ap-northeast-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
